### ISSUE TITLE
Come up with a question to ask to the customer

### ISSUE THREAD

**Issue by berk94** [bounswe/bounswe2017group2#15]
Every team member should post at least one question in the comments.

**Comment by berk94** [comment]
Can all the users create event (concert) pages?

**Comment by elifguler96** [comment]
Can all users create new tags or should the tags be predefined?

**Comment by furkansenharputlu** [comment]
How will the users be notified about news?News feed or notification ?

**Comment by oguzhangoller** [comment]
Is there going to be an artist verification system ? How is it going to work ?

**Comment by bekir16** [comment]
Who can rate or comment the concerts?(just attended people or everyone)

**Comment by HalukKaraevli** [comment]
Should the recommended events respond according to will attend section along with attended part?
