### ISSUE TITLE
Create an image field for Concert

### ISSUE THREAD

**Issue by berk94** [bounswe/bounswe2017group2#156]
Decide where we want to store the images and how we can do so (by url, bitmaps...).

**Comment by eneshecan** [comment]
While the user is creating a concert, he/she should be able to upload an image.

**Comment by eneshecan** [comment]
Understood how Django handles files with forms.

**Comment by eneshecan** [comment]
Implemented uploading an image via /upload/ endpoint with a form.

**Comment by eneshecan** [comment]
Retrieving images via /concert_image/pk endpoint implemented.

**Comment by eneshecan** [comment]
Implemented user and concert image uploading via /upload_user_image/ ve /upload_concert_image/ endpoints.

**Comment by berk94** [comment]
Good work Enes!
