### ISSUE TITLE
Create a one-to-many relationship between Concert and Rating

### ISSUE THREAD

**Issue by berk94** [bounswe/bounswe2017group2#157]
Each Concert will have ratings in various criteria:
- Concert atmosphere (how was the location, food, people)
- Artist costumes
- Music quality
- Stage show

For this, we will also need to add a Type field to the Rating class, indicating the type of the rating. e.g. 
if Type = 0 , the Rating object is for concert atmosphere
if Type = 1 , the Rating object is for artist costumes
if Type = 2 , the Rating object is for music quality
if Type = 3 , the Rating object is for stage show

**Comment by HalukKaraevli** [comment]
The names of the rating types; 
- concert_atmosphere, 
- artist_costumes, 
- music_quality, 
- stage_show 
will be the fields in the ratings object. Each field will be an integer whose value is between 1 and 10.
