### ISSUE TITLE
Revise project requirements

### ISSUE THREAD

**Issue by elifguler96** [bounswe/bounswe2017group2#18]
Revise the project requirements according to the notes we took and the feedback from our customer

**Comment by elifguler96** [comment]
I revised some parts of the requirements. The part that need revision are:
- Non-functional requirements:
   - Please revise according to what we discussed in the PS. All the requirements should be measurable; for instance, Req. 6.1 is very ambiguous, you may want to specify a time. There are many requirements like this, please revise all of them.
- Glossary:
   - Please add a glossary.
- Functional requirements:
   - Please add requirements about login and signup. In these requirements, you may make the distinction between registered/non-registered users, and then continue on to their requirements.
   - Also, please add a requirement about the concert page merging that we talked about in class
   - Please revise the requirements about confirming if an information is correct, according to the crowdsourced method we discussed in class. For instance, each separate information in a concert page should have an option to either confirm or deny (with the user possibly entering a suggestion). If enough denies are collected, the system may automatically change that information.

**Comment by berk94** [comment]
I added a Glossary.

**Comment by berk94** [comment]
Added sign-in and sign-up to user requirements
