### ISSUE TITLE
Make 3 Scenarios for Use Diagram Until 10 pm Monday

### ISSUE THREAD

**Issue by HalukKaraevli** [bounswe/bounswe2017group2#24]
The Scenarios should look like this:

Actor(s):
Goal:
Preconditions:
*
*
Steps
*
*
Postconditons: (?) I need an explanation for this.

**Comment by HalukKaraevli** [comment]
Also in order to prevent doing same page everyone should give their topics of scenarios.
for instance;
Sign in
Unregistered Search

**Comment by elifguler96** [comment]
I added the use case diagram and also did Create Concerts, View Concert Page, and View Profile Page parts.

**Comment by bekir16** [comment]
I did the Edit Account,Search Another User,Search Concert.

**Comment by HalukKaraevli** [comment]
I made:
-Get Notifications
-Follow Another User
-Report Other Users

**Comment by berk94** [comment]
I completed:
- Registration
- Sign in
- Get Recommendations

**Comment by furkansenharputlu** [comment]
I finished: 

-Social Media Integration
-Reporting Concert Information

**Comment by furkansenharputlu** [comment]
As Elif said, I removed social media integration part. Now there are 16 cases.
