### ISSUE TITLE
Implement search functionality for Top Navigation

### ISSUE THREAD

**Issue by buraksofu** [bounswe/bounswe2017group2#242]
Dummy search bar in the top navigation component should function and list results in the main page.

**Comment by berk94** [comment]
Can you also make the navigation bar stay fixed at the top when the user scrolls down? Thanks!

**Comment by buraksofu** [comment]
Nice point, I will look into it. I will also put an option for advanced search with a good design.

**Comment by buraksofu** [comment]
Search is done, sticky top bar packages are problematic with the latest versions that we use, so cancelled for now.
