### ISSUE TITLE
Implement report false concert information

### ISSUE THREAD

**Issue by berk94** [bounswe/bounswe2017group2#276]
For this, we have a Report class, which has a 'report_type' field that indicates which field of the Concert the report is for.

REPORT_TYPES = (
        ("NAME","name"),
        ("ARTIST","artist"),
        ("DATE_TIME","date_time"),
        ("DESCRIPTION","description"),
        ("LOCATION","location"),
        ("MIN_PRICE","min_price"),
        ("MAX_PRICE","max_price"),
        ("SELLER_URL","seller_url"),
        ("IMAGE","image"),
    )

if the length of upvoters reaches a threshold, let's say 10, the related Concert information will be replaced by the suggestion.

**Comment by berk94** [comment]
Implemented the model, create/delete and upvote/cancel_upvote for Concert Report

**Comment by berk94** [comment]
Finished. IMPORTANT:
When providing Artist or Location, enter the JSON object in String form. For instance:
"report_type": "ARTIST",
"suggestion": "{ \"images\": [ { \"height\": 500, \"url\": \"https://i.scdn.co/image/4178a5a92fae5c5a67cfe9ba113ea875318952b8\", \"width\": 500 }, { \"height\": 200, \"url\": \"https://i.scdn.co/image/4cc52c3bfa7a6e56447918b9a30ab4aea2086159\", \"width\": 200 }, { \"height\": 64, \"url\": \"https://i.scdn.co/image/19a5dc46891668b276e9375849b93b1e2cb0e620\", \"width\": 64 } ], \"spotify_id\": \"2yMN0IP20GOaN6q0p0zL5k\", \"name\": \"Tarkan\" }"
}

**Comment by spctr** [comment]
Can a set of tags be suggested?

**Comment by berk94** [comment]
no

**Comment by berk94** [comment]
Bugs solved.
