### ISSUE TITLE
Improve Concert recommendations

### ISSUE THREAD

**Issue by berk94** [bounswe/bounswe2017group2#278]
Consider:
- Concerts of the Artists related to the ones whose concerts our user has already attended
- Concerts that other users are attending who have attended concerts common with our user
- Concerts attended by the users that our user follows
- Concerts that have semantic tags related to the ones in concerts that our user already attended
- Add your ideas...

**Comment by eneshecan** [comment]
Recommending concerts attended by the users that our user follows implemented.

**Comment by HalukKaraevli** [comment]
Done
