### ISSUE TITLE
Frontend should be deployed on AWS

### ISSUE THREAD

**Issue by spctr** [bounswe/bounswe2017group2#297]
Front end files should be built and uploaded to AWS.

**Comment by berk94** [comment]
Front-end is now deployed on AWS.
Homepage URL: http://34.210.127.92:8000/home/

Could you fix the /admin endpoint? Thanks!

**Comment by spctr** [comment]
Pushed the fix to frontend-deployed branch, sending pull request now.

**Comment by buraksofu** [comment]
Front-end is deployed.
