### ISSUE TITLE
Everyone should contribute to the Test Plan

### ISSUE THREAD

**Issue by berk94** [bounswe/bounswe2017group2#54]

**Comment by berk94** [comment]
I finished:
- Registration
- Create Concert
Could you please double-check?

**Comment by furkansenharputlu** [comment]
I made:

- Search another user

- Search a concert

@bekir16 @berk94 Please check them.

**Comment by eneshecan** [comment]
I completed the plans,

- Follow another user

- Attend to a concert

**Comment by elifguler96** [comment]
I did:
* Sign-in
* Get Recommendation

**Comment by oguzhangoller** [comment]
I did :

- View Concert Page
