### ISSUE TITLE
Everyone should contribute to the documentation of ConcertAPI

### ISSUE THREAD

**Issue by elifguler96** [bounswe/bounswe2017group2#66]
Everyone should contribute to the documentation of ConcertAPI

**Comment by elifguler96** [comment]
I did:
* Get all concerts
* Get a specific concert

**Comment by berk94** [comment]
I finished:
- Create Concert [POST]
- Modify Concert [PUT]

**Comment by oguzhangoller** [comment]
I completed 
-Create User[POST]

**Comment by furkansenharputlu** [comment]
I made:

- Get all users [GET]
